import Header from '@/components/navigation/Header';
import { Inter } from 'next/font/google';
import './globals.css';

// Carrega a Inter via Next.js otimizada
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children } ) {
  return (
    <html lang="pt-BR" className={`${inter.variable} font-sans`}>
      <body className="antialiased">
        <Header />
         <main className="flex-grow">
         {children }
         </main>
      </body>
    </html>
  );
}
